services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: alerts-backend-dev
    ports:
      - '8080:8080'
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run start
    networks:
      - alerts-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: alerts-frontend-dev
    ports:
      - '3000:3000'
    env_file:
      - ./frontend/.env.local
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - backend
    networks:
      - alerts-network

networks:
  alerts-network:
    driver: bridge
