import { auth0 } from '@/lib/auth0';
import Footer from '../components/Footer';
import Header from '../components/Header';
import '../globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth0.getSession();
  const user = session?.user || null;

  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen ">
        {user && <Header user={user}></Header>}
        <main className="grow bg-gray-100">{children}</main>
        {<Footer />}
      </body>
    </html>
  );
}
